# Generated by Django 5.0.7 on 2024-07-31 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer1app', '0002_remove_opportunity_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='companyid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
