# Generated by Django 5.0.7 on 2024-07-31 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer1app', '0003_opportunity_companyid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sdgoal1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sdgoal2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer1app.opportunity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteer1app.user')),
            ],
            options={
                'unique_together': {('user', 'opportunity')},
            },
        ),
    ]
