# Generated by Django 5.0.7 on 2024-08-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer1app', '0004_user_sdgoal1_user_sdgoal2_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sdgoal1',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sdgoal2',
        ),
        migrations.AddField(
            model_name='opportunity',
            name='sdgoal1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='sdgoal2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
