# Generated by Django 5.0.7 on 2024-08-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer1app', '0005_remove_user_sdgoal1_remove_user_sdgoal2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='completedStatus',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='avg_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='completion_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
