# Generated by Django 5.0.7 on 2024-08-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer1app', '0006_application_completedstatus_application_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
