# Generated by Django 5.0.7 on 2024-08-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer1app', '0007_alter_application_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='completedStatus',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='application',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
