# Generated by Django 5.0.7 on 2024-08-02 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer1app', '0009_alter_application_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avg_rating',
        ),
        migrations.RemoveField(
            model_name='user',
            name='completion_rate',
        ),
    ]
